import type { Product } from "./product-data";
import { products } from "./product-data";

export const familiesZh = [
  { id: "doors", title: "门与隔断系统", text: "以吊趟、折叠、中轴和屏风系统，为建筑空间创造灵活而轻盈的边界。" },
  { id: "bathroom", title: "卫浴门系统", text: "围绕不同墙体、开启方向和安装条件开发的极窄、平墙与内开解决方案。" },
  { id: "invisible", title: "铝木与隐形门", text: "适配护墙板或抹灰饰面的门系统，让门扇与周围墙面自然融为一体。" },
  { id: "wall", title: "门墙柜系统", text: "连接储物、展示、墙板与灯光的一体化铝木建筑系统。" },
  { id: "wardrobe", title: "衣帽间系统", text: "通过开放层架、玻璃柜门与协调灯光，构建可自由组合的衣帽间。" },
  { id: "display", title: "展示与装饰柜", text: "适用于住宅与商业空间的玻璃柜、酒架和发光展示系统。" },
];

const translations: Record<string, Partial<Product>> = {
  "4510-concealed-sliding": {
    name: "4510 吊趟门", category: "暗装轨道吊趟门", tagline: "轨道隐于顶，移动轻若无声。",
    description: "4510 采用抹灰款预埋暗装轨道。自带悬挂系统的阻尼吊轮可在安装后调节水平角度，在保持顶面干净完整的同时，实现顺滑、静谧且可维护的移动体验。",
    quickSpecs: [{ label: "玻璃", value: "8 mm 钢化玻璃" }, { label: "单扇承重", value: "最高 150 kg" }, { label: "轨道", value: "单 / 双 / 三轨" }, { label: "门重", value: "24 kg/m²" }],
    features: [{ title: "暗装轨道", text: "预埋轨道隐藏于完成面内，保持顶面线条连续。" }, { title: "静音悬挂", text: "阻尼吊轮让门扇移动柔和、顺滑且安静。" }, { title: "现场可调", text: "悬挂系统可在安装后调平，并适应不同现场条件。" }, { title: "便捷维护", text: "先预埋、后装门，门扇可随时拆卸、调节与维护。" }],
    applications: ["客餐厅隔断", "住宅套房", "会议空间", "酒店与会所"],
    configuration: ["单轨、双轨或三轨", "单扇或多扇联动", "抹灰款预埋暗装轨道", "210 mm 拉手，默认距地 1050 mm"],
    technical: [{ title: "轨道与吊顶准备", intro: "轨道需要在吊顶完成前协调预埋。", items: ["抹灰款预埋轨道", "适配 9 mm 石膏板加抹灰刮腻子", "支持单轨、双轨和三轨", "完成轨道与吊顶后再安装门扇"] }, { title: "门扇最小宽度", items: ["单轨、双轨双阻尼：单扇最小 530 mm", "联动门双阻尼：单扇最小 580 mm", "最终尺寸需结合玻璃重量和五金配置确认"] }, { title: "五金系统", items: ["阻尼吊轮", "带螺纹挂板的单轮", "阻尼限位块", "单扇最高额定承重 150 kg"] }],
  },
  "4010-linked-sliding": {
    name: "4010 吊趟门", category: "多扇联动吊趟门", tagline: "多扇联动，一次开启更大空间。",
    description: "4010 面向大开口空间，可实现多扇门同步叠加开启与关闭，并支持一至五轨的组合。定制防摆结构保持门扇稳定，让大尺度开合兼具秩序与轻盈。",
    quickSpecs: [{ label: "玻璃", value: "8 mm 钢化玻璃" }, { label: "单扇承重", value: "最高 150 kg" }, { label: "轨道", value: "1 至 5 轨" }, { label: "最小宽度", value: "400 mm" }],
    features: [{ title: "多扇联动", text: "门扇依次同步开启与关闭，一次操作完成大空间切换。" }, { title: "大开口专属", text: "一至五轨组合适配住宅、酒店和商业空间的大跨度洞口。" }, { title: "轨道可扩展", text: "多段轨道可根据项目长度进行连续组合。" }, { title: "定制防摆", text: "针对项目配置防摆导向，减少门扇晃动。" }],
    applications: ["大尺度客厅", "宴会厅与酒店空间", "会议室", "灵活商业空间"],
    configuration: ["单轨至五轨", "多扇联动开启", "定制防摆导向", "170 mm 拉手，默认距地 1050 mm"],
    technical: [{ title: "门扇与轨道规划", items: ["支持单轨、双轨、三轨、四轨和五轨", "多扇叠加同步开启关闭", "轨道可按大跨度洞口延伸组合", "门扇数量由净开口和收纳空间共同决定"] }, { title: "核心参数", items: ["门重：24 kg/m²", "单扇最高承重：150 kg", "双阻尼单扇最小宽度：400 mm", "8 mm 钢化玻璃"] }],
  },
  "4516-slim-sliding": {
    name: "4516 吊趟门", category: "极窄吊趟门", tagline: "删繁至简，只留下恰到好处的比例。",
    description: "4516 以极窄铝框和精确比例打破传统边界。吊趟结构结合钢化玻璃与双阻尼移动，让每一毫米的细节都服务于轻盈、耐久与秩序。",
    quickSpecs: [{ label: "玻璃", value: "8 mm 钢化玻璃" }, { label: "单扇承重", value: "最高 150 kg" }, { label: "轨道", value: "单 / 双 / 三轨" }, { label: "门重", value: "24 kg/m²" }],
    features: [{ title: "极窄边框", text: "精细的铝合金线条弱化空间之间的视觉边界。" }, { title: "比例控制", text: "依据开口尺度、门扇宽度和玻璃重量优化分格。" }, { title: "双阻尼移动", text: "开合过程柔和受控，提升日常使用的安静感。" }, { title: "灵活组合", text: "可采用单轨、多轨或多扇联动方式。" }],
    applications: ["住宅空间隔断", "衣柜与衣帽间", "书房", "精品商业空间"],
    configuration: ["单轨、双轨或三轨", "单扇或联动门", "210 mm 拉手，默认距地 1050 mm", "钢化玻璃与项目定制颜色"],
    technical: [{ title: "最小门扇宽度", items: ["单扇双阻尼：最小 580 mm", "联动门双阻尼：单扇最小 520 mm", "最终比例需结合门扇重量确认"] }, { title: "承重与玻璃", items: ["门重：24 kg/m²", "单扇最高承重：150 kg", "8 mm 钢化玻璃", "单轨、双轨和三轨可选"] }],
  },
  "4512-folding": {
    name: "4512 多扇折叠门", category: "多扇折叠门", tagline: "小空间，也能获得更完整的释放。",
    description: "4512 通过二至四扇窄幅玻璃门，将完整的空间边界折叠收拢。门扇可向左、向右或对开，并选择向内或向外折叠，在通透与私密之间保持轻盈平衡。",
    quickSpecs: [{ label: "门扇", value: "2 至 4 扇" }, { label: "高度", value: "600–2900 mm" }, { label: "单扇宽度", value: "350–600 mm" }, { label: "开启", value: "6 种方向" }],
    features: [{ title: "更大释放", text: "门扇折叠收拢于一侧，释放更多有效开口。" }, { title: "六种开启", text: "可左开、右开或对开，并选择向内或向外折叠。" }, { title: "窄幅门扇", text: "精细分格让折叠后的体积更紧凑。" }, { title: "项目适配", text: "二、三或四扇组合适应不同空间和动线。" }],
    applications: ["小户型住宅", "厨房与客厅分隔", "步入式衣帽间", "酒店套房"],
    configuration: ["2–3 扇或 2–4 扇", "左开、右开或对开", "向室内或向室外折叠", "吊轮挂盒与天地轴配合"],
    technical: [{ title: "门扇尺寸范围", items: ["门扇高度：600–2900 mm", "常规单扇宽度：350–600 mm", "部分四扇组合单扇宽度为 350–500 mm", "最终宽度由折叠方向和五金配置决定"] }, { title: "开启方向", items: ["向左、向室内折叠", "向左、向室外折叠", "向右、向室内折叠", "向右、向室外折叠", "对开、向室内或室外折叠"] }],
  },
  "4516-pivot": {
    name: "4516 中轴 / 偏轴门", category: "中轴与偏轴门", tagline: "改变支点，重新定义空间的开合。",
    description: "4516 以中轴或偏轴形成大尺度旋转开启。上下极窄边框、90° 随停与多种承重五金，让入口在功能与视觉之间保持从容平衡。",
    quickSpecs: [{ label: "玻璃", value: "8 mm 钢化玻璃" }, { label: "最高门高", value: "2950 mm" }, { label: "随停", value: "90°" }, { label: "轴位", value: "中轴 / 偏轴" }],
    features: [{ title: "平衡旋转", text: "根据通行、尺度与视觉需求选择中轴或偏轴位置。" }, { title: "90° 随停", text: "门扇可在直角位置停留，让通行状态更加清晰。" }, { title: "上下极窄", text: "窄边框控制大门扇的视觉重量。" }, { title: "多种五金", text: "国产与进口、轻型与重型五金适应不同项目。" }],
    applications: ["入户与门厅", "客厅空间", "高管办公室", "酒店与会所"],
    configuration: ["中轴或偏轴", "室内或有遮蔽的室外环境", "轻型或重型五金", "轴位尺寸按五金配置选择"],
    technical: [{ title: "五金规划", items: ["国产五金标示最大门扇宽度：1300 mm", "进口五金标示最大门扇宽度：1800 mm", "85、130、150 mm 轴位需结合五金选择", "最终承重与尺寸需经项目技术确认"] }, { title: "门扇要点", items: ["标示最高高度：2950 mm", "8 mm 钢化玻璃", "90° 随停", "中轴与偏轴均可配置"] }],
  },
  "bathroom-door-collection": {
    name: "卫浴门系列", category: "极窄、平墙与内开卫浴门", tagline: "在私密空间的入口，保持精确与克制。",
    description: "卫浴门系列包含 4516、4010 平开门、外平内开隐形门和外包内开门。每套系统都围绕墙体厚度、开启方向、玻璃朝向和安装缝隙进行协调。",
    quickSpecs: [{ label: "上左右缝隙", value: "≤ 3 mm" }, { label: "锁高", value: "1050 mm" }, { label: "合页承重", value: "70–80 kg" }, { label: "玻璃玉砂面", value: "默认朝室外" }],
    features: [{ title: "4516 平开门", text: "天地轴承重与一体锁相互配合，适配最小 80–90 mm 墙体。" }, { title: "4010 平开门", text: "26 mm 一体小门套，适配约 57–64 mm 起的墙体条件。" }, { title: "外平内开", text: "玻璃与外侧墙面保持同一平面，门扇向内开启。" }, { title: "外包内开", text: "门套外置、门扇内开，释放更多室内使用空间。" }],
    applications: ["住宅卫浴", "酒店套房", "康养空间", "私属衣帽区"],
    configuration: ["左锁或右锁", "按型号选择内开或外开", "单包套或双包套", "玉砂或项目指定玻璃朝向"],
    technical: [{ title: "4516 卫浴平开门", items: ["门套与门扇左、右、顶部缝隙 ≤3 mm", "门扇离地缝隙 ≤13 mm", "门锁默认安装高度 1050 mm", "精铸天地轴合页最大承重 70 kg", "不同包套最小墙厚通常为 80 或 90 mm"] }, { title: "4010 卫浴平开门", items: ["26 mm 一体极窄门套", "门套与门扇左、右、顶部缝隙 ≤3 mm", "门扇离地缝隙 ≤13 mm", "不同包套最小墙厚通常为 57 或 64 mm"] }, { title: "外平与内开型号", items: ["门扇离地缝隙 ≤10 mm", "侧隐可调合页最大承重 80 kg", "门高 1800–2800 mm 配 3 个合页；2800–3000 mm 配 4 个", "平墙或外包条件对应不同墙面准备方式"] }, { title: "现场测量", intro: "生产前应完成门洞复核。", items: ["上、中、下三点测量宽高，取最小值", "上、中、下及左右测量墙厚，取最大值", "误差超过 5 mm 的门洞应先修正", "检查横梁、台阶和丁字墙是否需要加做基层", "站在室外确认锁位与内开、外开方向"] }],
  },
  "invisible-aluminium-wood-doors": {
    name: "隐形铝木门系列", category: "护墙与抹灰款隐形门", tagline: "让门成为墙面的一部分。",
    description: "隐形铝木门面向护墙板或抹灰墙面。隐藏式铝框让门扇、墙板与周围柜体形成连续完整的建筑表面，在保持私密功能的同时强化空间统一感。",
    quickSpecs: [{ label: "极窄边框", value: "25 mm 可选" }, { label: "木饰面", value: "9 mm" }, { label: "合页承重", value: "最高 80 kg" }, { label: "最小墙厚", value: "80 mm" }],
    features: [{ title: "25 极窄门", text: "门套外置、门扇内开，以克制的铝线条连接功能与美感。" }, { title: "护墙款隐形门", text: "适配 9 或 18 mm 护墙板，实现门墙同面。" }, { title: "抹灰款隐形门", text: "门框配合抹灰与腻子收口，让开口隐于墙内。" }, { title: "门墙柜一体", text: "门、墙板和柜体可共享同一种材料与分缝逻辑。" }],
    applications: ["卧室与私密空间", "一体化护墙系统", "酒店套房", "高端住宅走廊"],
    configuration: ["单包套或双包套", "外平内开或外平外开", "9 mm 护墙板或抹灰准备", "左锁或右锁"],
    technical: [{ title: "25 极窄铝木门", items: ["左右及顶部缝隙 ≤3 mm", "离地缝隙 ≤10 mm", "9 mm 木饰面板", "门锁默认高度 1050 mm", "最小墙厚 80 mm"] }, { title: "护墙款隐形门", items: ["适配 9 或 18 mm 护墙板系统", "门框与完成后的墙板平面齐平", "侧隐可调合页最大承重 80 kg", "根据门高配置 3 或 4 个合页"] }, { title: "抹灰款隐形门", items: ["门框为平墙抹灰收口准备", "典型构造包括 3 mm 腻子/批灰和 6 mm 玻镁板", "最小墙厚 80 mm", "可选择内开或外开形式"] }],
  },
  "open-wardrobe-collection": {
    name: "开放式衣帽间系列", category: "立柱式与壁挂式衣帽间", tagline: "用结构、灯光与收纳构成开放秩序。",
    description: "从单立柱、圆立柱到发光开放格和壁挂悬浮层架，五种模块化语言让衣帽间不再只是封闭柜体，而成为空间中的建筑展示系统。",
    quickSpecs: [{ label: "系统", value: "5 个系列" }, { label: "结构", value: "铝合金" }, { label: "层板", value: "玻璃 / 木板" }, { label: "灯光", value: "一体化" }],
    features: [{ title: "雷克", text: "单立柱结构协调金属、玻璃、灯光与皮革细节。" }, { title: "铂恩与贝丝", text: "方形或圆形立柱形成不同的结构语言。" }, { title: "岚格", text: "立柱灯光让开放收纳转化为精致展示。" }, { title: "攸库", text: "隐藏龙骨支撑悬浮层板、抽屉与斜挂鞋架。" }],
    applications: ["步入式衣帽间", "开放式更衣区", "服装零售", "住宅收纳墙"],
    configuration: ["单立柱、靠墙或顶地立柱", "圆形或方形立柱", "玻璃或木质层板", "衣通、鞋架与抽屉配件"],
    technical: [{ title: "系统系列", items: ["雷克单立柱衣帽间", "铂恩靠墙或顶地立柱系统", "贝丝圆立柱衣帽间", "岚格发光开放式衣帽间", "攸库壁挂式衣帽间"] }, { title: "走线与调节", items: ["可通过墙体或顶部协调走线", "部分脚座可上下调节 12 mm", "灯光可集成立柱或层板线条内", "所有配件依据最终收纳需求布置"] }],
  },
  louver: {
    name: "格栅隔断系列", category: "滑动格栅与固定屏风", tagline: "在同一个建筑层次中，平衡私密、光线与移动。",
    description: "格栅隔断系列将通高滑动门扇与固定屏风纳入极窄铝框体系。竖向格栅与几何网格在保留自然光和空气感的同时过滤视线，为会议室、衣帽间和住宅空间形成精确而灵活的边界。",
    quickSpecs: [{ label: "形式", value: "通顶" }, { label: "私密性", value: "视线过滤" }, { label: "边框", value: "极窄铝框" }, { label: "设计", value: "项目定制" }],
    features: [{ title: "层叠私密", text: "格栅与几何网格柔化视线，却不让空间显得封闭。" }, { title: "极窄框架", text: "细窄铝框构成克制有序的建筑网格。" }, { title: "按项目定尺", text: "门扇数量和整体尺寸依据洞口进行设计。" }, { title: "饰面协调", text: "框架、填充与格栅颜色可与室内材料统一。" }],
    applications: ["住宅隔断", "衣柜门", "会议空间", "酒店与会所"], configuration: ["移动或固定扇组合", "单扇或多扇布局", "竖向格栅或几何网格填充", "阳极氧化或喷涂铝材饰面"],
  },
  vetro: {
    name: "Vetro 玻璃衣柜", category: "玻璃衣柜系统", tagline: "以通透和比例表达衣柜。",
    description: "Vetro 由通顶极窄铝框与烟熏玻璃门构成。通透结构降低大面积柜体的视觉重量，一体灯光清晰呈现层板、衣通和陈列物品。",
    quickSpecs: [{ label: "柜门", value: "烟熏玻璃" }, { label: "边框", value: "铝合金" }, { label: "灯光", value: "一体化" }, { label: "设计", value: "项目定制" }],
    features: [{ title: "通顶节奏", text: "重复的竖向模数形成平静连续的立面。" }, { title: "烟熏玻璃", text: "柜内物品以柔和剪影呈现在反射玻璃之后。" }, { title: "一体灯光", text: "柜内 LED 提高可视性，并增强内部层次。" }, { title: "灵活内构", text: "层板、衣通和收纳配件按项目需求组合。" }],
    applications: ["卧室", "步入式衣帽间", "精品零售", "住宅更衣区"], configuration: ["定制柜格宽度与高度", "透明、烟熏或反射玻璃", "层板与衣通组合", "暖色一体化 LED 灯光"],
  },
  linea: {
    name: "Linea 门墙柜系统", category: "门墙柜一体系统", tagline: "以模块化框架整合收纳、展示与衣帽功能。",
    description: "Linea 将开放层板、封闭柜体、衣通和线性灯光整合于同一墙面系统。极窄立柱组织立面，悬挑层板和悬挂柜体让整体轻盈并可随空间变化。",
    quickSpecs: [{ label: "形式", value: "模块化墙面" }, { label: "收纳", value: "开放 / 封闭" }, { label: "层板", value: "玻璃 / 木板" }, { label: "灯光", value: "一体化" }],
    features: [{ title: "模块规划", text: "同一立柱网格可承载展示、衣帽和收纳功能。" }, { title: "开放与封闭", text: "层板、抽屉和整面柜门可在同一组合中混合。" }, { title: "线性灯光", text: "竖向和层板灯光与模块共同规划。" }, { title: "贴合建筑", text: "直线、转角与回转组合可顺应房间几何。" }],
    applications: ["客厅", "衣帽区", "商业展示", "酒店套房"], configuration: ["通墙或局部组合", "开放层板与封闭柜体", "衣通与抽屉配件", "暖白一体化 LED 灯光"],
  },
  cellar: {
    name: "Cellar 酒架系统", category: "铝板与亚克力酒架", tagline: "为酒藏构建轻盈、发光的铝合金秩序。",
    description: "Cellar 以极窄铝立柱、玻璃层板和倾斜酒架构成模块化展示墙。开放网格让大容量酒藏清晰可读，一体灯光为私人酒窖、餐厅和会所营造克制的展示背景。",
    quickSpecs: [{ label: "结构", value: "铝合金" }, { label: "陈列", value: "倾斜酒瓶" }, { label: "布局", value: "可扩展" }, { label: "灯光", value: "一体化" }],
    features: [{ title: "大容量", text: "重复模数有序容纳酒藏，同时保持视觉轻盈。" }, { title: "倾斜展示", text: "斜置支撑让酒标清晰可见并保持排列整齐。" }, { title: "一体灯光", text: "顶部灯光为每个模数提供均匀的展示照明。" }, { title: "可扩展网格", text: "模块结构可随墙面宽度连续延伸。" }],
    applications: ["私人酒窖", "餐厅", "酒店与会所", "葡萄酒零售"], configuration: ["多种模数宽度", "酒架与玻璃层板组合", "沿墙、转角或房间式布局", "金属颜色与灯光协调"],
  },
  lume: {
    name: "展示与装饰柜系列", category: "玻璃展示柜与装饰柜", tagline: "以玻璃、材质与光线，精确框定每一件陈列。",
    description: "展示与装饰柜系列包含落地、壁挂与通高玻璃柜。极窄金属框、木质抽屉、格栅门面和一体化灯光可按项目组合，适用于酒具、艺术品、收藏品与商业陈列。",
    quickSpecs: [{ label: "形式", value: "落地 / 壁挂" }, { label: "门面", value: "玻璃 / 格栅" }, { label: "灯光", value: "一体化" }, { label: "设计", value: "项目定制" }],
    features: [{ title: "透明体量", text: "纤细框架与玻璃层板保留穿透柜体的视线。" }, { title: "多种形式", text: "落地、壁挂和通高柜体适应不同空间与收藏需求。" }, { title: "一体灯光", text: "层板、周边或背板灯光可与柜体构成一体设计。" }, { title: "陈列灵活", text: "层板、抽屉和门面组合适配酒具、艺术品与商业产品。" }],
    applications: ["家庭吧台", "客厅", "精品商业展示", "酒店与会所"], configuration: ["落地、壁挂或通高形式", "玻璃、格栅与木质门面组合", "层板、周边或背板灯光", "按项目定制高度、饰面与内部布局"],
  },
};

const galleryCaptionsZh: Record<string, string> = {
  "/products/manual/pivot-door-interior.jpg": "中轴与偏轴玻璃门围绕选定轴位旋转开启，形成大尺度且具有建筑感的通行界面。",
  "/products/manual/bathroom-door-interior.jpg": "极窄深色边框勾勒玉砂玻璃门，在保持私密性的同时维持克制的空间入口。",
  "/products/manual/bathroom-door-threshold.jpg": "平墙构造让卫浴入口安静地融入周围室内立面。",
  "/products/manual/bathroom-door-frosted.jpg": "通高玉砂玻璃保护私密，并保留轻盈完整的门扇比例。",
  "/products/manual/invisible-door-panelled-wall.jpg": "门扇、隐藏式门框与护墙板对齐为连续完整的建筑表面。",
  "/products/manual/invisible-door-dark-suite.jpg": "隐藏式门框让深色门扇自然隐入套房护墙立面。",
  "/products/manual/invisible-door-plaster-wall.jpg": "抹灰款门框让门洞消隐在干净连续的墙面完成层中。",
  "/products/real/1790(1).JPG": "暗装顶轨让通顶玻璃隔断保持安静、完整的顶面线条。",
  "/products/real/1788.JPG": "大跨度联动门在保持极窄边框的同时，充分释放客厅开口。",
  "/products/real/1787.JPG": "半透材质在多扇联动开口中柔化视线并保留光线。",
  "/products/real/1791(1).JPG": "极窄框架与定制拱形玻璃共同形成轻盈的空间入口。",
  "/products/real/1785.JPG": "图案玻璃为克制的通顶吊趟组合增加恰到好处的私密性。",
  "/products/real/1820(1).JPG": "左右对称折叠收拢，完整释放中央通行开口。",
  "/products/real/1821(1).JPG": "纹理玻璃保留私密感，门扇可紧凑折叠于墙侧。",
  "/products/real/1842.JPG": "完整衣帽墙整合衣通、抽屉与开放层板。",
  "/products/real/1841(1).JPG": "单立柱结构承载衣通、层板与配件托盘。",
  "/products/real/1843.JPG": "暖金属饰面的衣通、托盘与立柱节点。",
  "/products/real/1801(1).JPG": "一体化灯光为层板与挂衣区建立清晰节奏。",
  "/products/real/1808(1).JPG": "通透模块网格连接展示、收纳与衣帽功能。",
  "/products/real/1809(1).JPG": "深色铝合金模块围合出连续开放式衣帽间。",
  "/products/real/1831.JPG": "圆立柱组织长层板、灯光与悬挂底柜。",
  "/products/real/1832.JPG": "层板、悬挂柜和影音设备共享同一结构网格。",
  "/products/real/1833.JPG": "通顶立柱与连续层板灯光形成平衡立面。",
  "/products/real/1834.JPG": "线性 LED 隐于木质层板下方，照明均匀而克制。",
  "/products/real/1835.JPG": "极窄墙轨承托层板，同时弱化可见固定件。",
  "/products/real/1836.JPG": "紧凑连接件将层板精确锁定于圆立柱。",
  "/products/real/1837.JPG": "灯带与微调脚座统一于同一结构语言。",
  "/products/real/1838.JPG": "墙面支撑增强开放系统稳定性，同时保持轻盈外观。",
  "/products/real/1839.JPG": "重复立柱让宽幅安装仍保持准确、连续的节奏。",
  "/products/real/1789.JPG": "滑动格栅遮挡衣帽间视线，同时保留空气感和空间层次。",
  "/products/real/1786.JPG": "高密度几何格栅在不完全封闭空间的情况下建立私密边界。",
  "/products/real/1810(1).JPG": "通透玻璃衣帽间让收纳成为室内建筑的一部分。",
  "/products/real/1800(1).JPG": "玻璃层板与暖色金属框架构成连续衣帽展示网格。",
  "/products/real/1854.JPG": "极窄立柱与发光层板为艺术收藏打造定制展示墙。",
  "/products/real/1816(1).JPG": "悬挑层板和悬挂抽屉让整面收纳保持轻盈。",
  "/products/real/1817(1).JPG": "挂衣、展示和抽屉收纳被统一到同一墙面立面。",
  "/products/real/1840.JPG": "层板、衣通与抽屉模块组成可灵活变化的商业展示墙。",
  "/products/real/1848.JPG": "封闭柜体、吧台储物与透明展示在同一立面中对齐。",
  "/products/real/1851.JPG": "内嵌层板为通顶柜墙带来深度与受控照明。",
  "/products/real/1855.JPG": "圆弧柜门柔化模块网格，并围合出连续发光壁龛。",
  "/products/real/1856.JPG": "圆角柜体与线性灯光共同形成连续的建筑构图。",
  "/products/real/1857.JPG": "开放发光格与悬挂封闭模块组成高密度收纳墙。",
  "/products/real/1858.JPG": "极细立柱与薄层板在通顶窗前构成发光书墙。",
  "/products/real/1829.JPG": "高密度酒瓶网格与倒挂杯架在极窄柜格内提升容量。",
  "/products/real/1852.JPG": "独立发光支托让通顶酒墙成为精确的陈列装置。",
  "/products/real/1802(1).JPG": "透明玻璃柜体与横向百叶正面取得展示与遮挡的平衡。",
  "/products/real/1803(1).JPG": "暖色内灯透过细密竖向格栅呈现柜内陈列。",
  "/products/real/1804(1).JPG": "玻璃侧板、细脚与连续百叶构成长型低柜。",
  "/products/real/1806(1).JPG": "悬挂式玻璃柜在保护陈列品的同时保持墙面轻盈。",
  "/products/real/1807(1).JPG": "双组壁挂玻璃柜将小尺度展示区转化为发光焦点。",
  "/products/real/1824(1).JPG": "玻璃、深色金属与木质抽屉组合为通顶展示塔。",
  "/products/real/1825(1).JPG": "中部实木抽屉由两侧铰接玻璃门保护。",
  "/products/real/1826.JPG": "开启状态呈现紧凑占地与通高收纳方式。",
  "/products/real/1827(1).JPG": "暖光突出透明柜体内部的榫接木抽屉。",
  "/products/real/1849.JPG": "电源、层板与发光艺术背板整合日常灵活收纳。",
  "/products/real/1850.JPG": "发光山水背板让紧凑柜体成为具有氛围感的陈列装置。",
  "/products/new-2026/1887.webp": "木饰面门扇沿顶部多轨系统移动，地面保持完整清爽。",
  "/products/new-2026/1888.webp": "四色门扇组合直观呈现多轨规划、材质与色彩选择。",
  "/products/new-2026/1889.webp": "开启状态可见隐藏合页，门框与深色护墙板保持协调。",
  "/products/new-2026/1890.webp": "同色门扇关闭后融入连续的深色墙面立面。",
  "/products/new-2026/1891.webp": "可批灰隐形门顺应弧形墙面，仅保留精确细缝。",
  "/products/new-2026/1893.webp": "开启视角呈现隐藏门框，关闭后门扇可与墙面齐平。",
  "/products/new-2026/1894.webp": "通高门扇安静嵌入弧形白色墙面，以深色细边界定轮廓。",
  "/products/new-2026/1895.webp": "悬浮层板与地柜结合墙板分格和隐藏灯光，形成完整电视墙。",
  "/products/new-2026/1896.webp": "通高玻璃展示柜齐平嵌入温润木饰面墙体。",
  "/products/new-2026/1897.webp": "发光展示格嵌入规整墙板网格，并与连续地柜统一。",
  "/products/new-2026/1898.webp": "壁挂玻璃柜、开放层板与悬浮地柜共同组成完整墙面系统。",
  "/products/new-2026/1899.webp": "纤薄金属层板与连续地柜形成精确而富有层次的展示界面。",
  "/products/new-2026/1911.webp": "发光层板、展示格与悬挂收纳共同构成通高墙面系统。",
  "/products/new-2026/1912.webp": "错落发光层板、玻璃展示塔与悬浮地柜围合电视区域。",
  "/products/new-2026/1914.webp": "纤薄折弯金属层板集成线性灯光，并弱化可见固定件。",
  "/products/new-2026/1915.webp": "侧面细节清楚呈现薄层板、挡边与隐藏灯带。",
  "/products/new-2026/1920.webp": "封闭收纳围合连续玻璃展示格，兼顾酒具、餐具与操作台。",
  "/products/new-2026/1921.webp": "通高发光网格将酒瓶、杯具与陈列品组织为清晰立面。",
  "/products/new-2026/1922.webp": "发光开放格整合酒瓶、倒挂杯架与日常操作台。",
};

export const zhProducts: Product[] = products.map((product) => {
  const translated = translations[product.slug];
  const productName = translated?.name ?? product.name;
  return {
    ...product,
    ...translated,
    gallery: product.gallery.map((image) => {
      const caption = galleryCaptionsZh[image.src] ?? image.caption;
      return { ...image, alt: `${productName}：${caption}`, caption };
    }),
  };
});

export function getZhProduct(slug: string) {
  return zhProducts.find((product) => product.slug === slug);
}
